apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: database-traffic-policy
  namespace: default
spec:
  selector: app == 'database'
  types:
  - Ingress
  ingress:
  - action: Allow
    http:
      methods: ["GET"]
    source:
      selector: app == 'summary'
  - action: Deny
    source:
      selector: app == 'Deny'